# Generated by Django 4.0 on 2022-04-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user'),
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='Lecturers',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
