# Generated by Django 4.0 on 2022-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
