# Generated by Django 4.0 on 2022-05-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
