# Generated by Django 4.0 on 2022-06-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignLecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course')),
                ('lecturer', models.ForeignKey(limit_choices_to={'lecturer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(upload_to='learning materials/')),
                ('assignedLect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assignlecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='assignments/')),
                ('assignedLect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assignlecturer')),
            ],
        ),
    ]
