# Generated by Django 4.0 on 2022-06-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_learningmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
