# Generated by Django 4.0 on 2022-06-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_course_user_course_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_Name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='course_credit',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseID',
            new_name='course_id',
        ),
    ]
