# Generated by Django 4.0 on 2022-06-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_name_course_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_credit',
            new_name='course_Credit',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_ID',
        ),
    ]
