# Generated by Django 4.0 on 2022-06-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_course_credit_course_course_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignlecturer',
            old_name='lecturer',
            new_name='lecturer_assigned',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='admin',
            new_name='admin_create',
        ),
    ]
