# Generated by Django 4.0 on 2022-06-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_lecturer_assignlecturer_lecturer_assigned_and_more'),
    ]

    operations = [
    ]
