# Generated by Django 4.0 on 2022-06-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_registercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_file', models.FileField(upload_to='submitted files/')),
                ('submit_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assignment')),
                ('course_registered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.registercourse')),
            ],
        ),
    ]
