# Generated by Django 4.0 on 2022-06-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercourse',
            old_name='user',
            new_name='student',
        ),
    ]
